###
POST http://localhost:3000/categories
Context-Type: application/json

{
    "name": "Category 1",    
}

###
PATCH http://localhost:3000/categories
Context-Type: application/json

{
    "id": "1",
    "name": "Category 1",    
    "description": "Description 1"
}

###
GET http://localhost:3000/categories

