### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name" : "Category 2"
}

###
PATCH http://localhost:3000/categories/84b982bb-6c2b-4aec-a13d-bc5e3af7429a
Content-Type: application/json

{
    "description": "Description 1"
}

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/b8038dcf-3a7b-43ab-86b8-b8823fdf24ed

###
GET http://localhost:3002/categories
